# официальный образ PostgreSQL
FROM postgres:17

# пакеты
RUN apt update && apt install -y \
    postgresql-contrib \
    #vim \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем переменные окружения
ENV POSTGRES_DB=Korotkova
ENV POSTGRES_USER=KorotkovaUser
ENV POSTGRES_PASSWORD=12345
ENV PGDATA=/var/lib/postgresql/data/pgdata

# Создаем директорию для хранения данных
RUN mkdir -p $PGDATA && chown -R postgres:postgres $PGDATA

# Открываем порт
EXPOSE 5432

# Устанавливаем точку монтирования для данных
VOLUME [«$PGDATA»]

# Запускаем PostgreSQL
CMD ["postgres"]